# Generated by Django 5.1.3 on 2024-12-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0002_remove_profiledb_decription_profiledb_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('text', models.TextField(max_length=200)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.profiledb')),
            ],
        ),
    ]
