# Generated by Django 5.1.3 on 2024-12-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdb',
            name='comments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='postdb',
            name='reaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
