# Generated by Django 5.1.3 on 2024-12-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledb',
            name='decription',
        ),
        migrations.AddField(
            model_name='profiledb',
            name='description',
            field=models.TextField(default='empty', null=True),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='back_profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
